application: criticalveloss
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/.*

- url: /js
  static_dir: static/js

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/.*

- url: /assessment/(.*)
  login: required
  script: main.app

- url: /inference/(.*)
  login: required
  script: main.app

- url: /topicnames/(.*)
  login: required
  script: main.app

- url: /userdetails/(.*)
  login: required
  script: main.app

- url: /masterybysubject/(.*)
  login: required
  script: main.app

- url: /pendingassessmentbysubject/(.*)
  login: required
  script: main.app


- url: /.*
  script: main.app


libraries:
- name: django
  version: "latest"



