application: criticalveloss
version: 1
runtime: python27
api_version: 1
threadsafe: true



handlers:
- url: /images
  static_dir: static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/.*

- url: /js
  static_dir: static/js

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/.*

- url: /testreport(.*)
  script: main.app

- url: /assessment(.*)
  script: main.app

- url: /subjectdetailsofstudent(.*)
  script: main.app

- url: /numberline/(.*)
  script: main.app

- url: /graph/(.*)
  script: main.app

- url: /getcourseinformation(.*)
  script: main.app

- url: /signout/(.*)
  script: main.app

- url: /inference(.*)
  script: main.app

- url: /topicnames/(.*)
  script: main.app

- url: /userdetails/(.*)
  script: main.app

- url: /masterybysubject/(.*)
  script: main.app

- url: /pendingassessmentbysubject/(.*)
  script: main.app


- url: /growthbysubject/(.*)
  script: main.app

- url: /readytolearnbysubject/(.*)
  script: main.app

- url: /notrecentlyloggedin_by_class/(.*)
  script: main.app

- url: /notrecentlyloggedinall_by_teacher/(.*)
  script: main.app

- url: /getclassdetailsbyteacher/(.*)
  script: main.app

- url: /notloggedinbyclass(.*)
  script: main.app

- url: /averagemasteryofsubject_topicwise(.*)
  script: main.app

- url: /averagemasterybysubjectbyclass(.*)
  script: main.app

- url: /subjectsofclass(.*)
  script: main.app

- url: /getspecialcourselist(.*)
  script: main.app

- url: /assessmentcoveragebyclass(.*)
  script: main.app

- url: /getclassdetailsbyteacher/(.*)
  script: main.app

- url: /readytolearnofsubject(.*)
  script: main.app

- url: /assessmentcoverageofsubject(.*)
  script: main.app

- url: /getgrowthofsubject(.*)
  script: main.app

- url: /averagemasterybysubjectallclass/(.*)
  script: main.app

- url: /learningprogress_by_date(.*)
  script: main.app

- url: /mastery_by_student_by_class(.*)
  script: main.app


- url: /gettopicwisescoreofsubject(.*)
  script: main.app

- url: /getreadytolearn_ofsubject(.*)
  script: main.app

- url: /getmasteryofsubject(.*)
  script: main.app

- url: /.*
  script: main.app


libraries:
- name: django
  version: "latest"
