
class Constant:
    STUDENT=1
    SCHOOL=2
    STATE=3
    QUESTION=4
    TOPIC=5
    ASSESSMENT=6
    NAME_ALIAS='N'
    QUESTION_TYPE_SINGLE=0
    QUESTION_TYPE_MULTIPLE=1
    NO_STUDENT_LEVEL_UPTO_25=0
    NO_STUDENT_LEVEL_UPTO_50=1
    NO_STUDENT_LEVEL_UPTO_75=2
    NO_STUDENT_LEVEL_UPTO_100=3
    STATE_IN_TOPIC=0
    STATE_OF_TOPIC=1
    STATE_CONTAINED_TOPICS="contains_topic_keys"
    SEX_MALE=0
    SEX_FEMALE=1
    
    

